# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfd-business:
    build:
      target: development
    image: ffc-sfd-business-development
    container_name: ffc-sfd-business-development
    ports:
      - "3003:3000"
      - "9003:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
